disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - leading_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Project/R.generated.swift
